version: "3"

volumes:
    volume_mongo:
    volume_s3:
    volume_rabbitmq:

secrets:
    MONGO_PASSWORD:
      file: secrets/mongo-password
    MONGO_URL:
      file: secrets/mongo-url
    JWT_SECRET_PHRASE:
      file: secrets/jwt-secret
    EMAIL_HOST:
      file: secrets/email-host
    EMAIL_PORT:
      file: secrets/email-port
    EMAIL_USER:
      file: secrets/email-user
    EMAIL_PASSWORD:
      file: secrets/email-password

networks:
    network_database:
    network_s3:
    network_rabbitmq:
          
services:

    rabbitmq:
        image: rabbitmq:management
        restart: unless-stopped
        ports: 
            - 8881:15672
            - 5672:5672
        volumes: 
            - volume_rabbitmq:/var/lib/rabbitmq
        networks: 
            - network_rabbitmq

    mongodb:
        image: mongo
        restart: always
        ports:
            - 27017:27017
        volumes:
            - volume_mongo:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/MONGO_PASSWORD
        secrets:
            - MONGO_PASSWORD
        networks:
            - network_database

    s3:
        image: lphoward/fake-s3
        restart: always
        ports:
            - 4569:4569
        volumes:
            - volume_s3:/fakes3_root
        networks:
            - network_s3

    # spotify-api:
    #     image: pcandido/spotify-api
    #     build: .
    #     restart: always
    #     depends_on:
    #         - mongodb
    #         - s3
    #         - rabbitmq
    #     ports: 
    #         - 8000:8000
    #     environment:
    #         PORT: 8000
    #         S3_ENDPOINT: http://s3:4569
    #         PASSWORD_RECOVERY_RABBITMQ_HOST: rabbitmq
    #     secrets:
    #         - MONGO_URL
    #         - JWT_SECRET_PHRASE
    #         - EMAIL_HOST
    #         - EMAIL_PORT
    #         - EMAIL_USER
    #         - EMAIL_PASSWORD
    #     networks:
    #         - network_database
    #         - network_s3
    #         - network_rabbitmq
          
